version: "3"

services:
  # KAFKA Communication Area
  # kafka area for serveral services communication will migrate all to confluent if we have budget
  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: onepiece-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2 
  # kafka
  kafka:
    image: confluentinc/cp-kafka
    container_name: onepiece-kafka
    ports:
      - 9094:9094
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: onepiece-topic-chat,onepiece-topic-chat-event,onepiece-gateway-event,onepiece-user-event,onepiece-trip-event,onepiece-locale-event,onepiece-chat-event
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # redis area
  # rate limit redis for gateway
  ratelimit:
    image: redis:alpine
    container_name: onepiece-gateway-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"

  # article server redis
  redisarticle:
    image: redis:alpine
    container_name: onepiece-article-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6380:6379"

  # trip server redis
  redistrip:
    image: redis:alpine
    container_name: onepiece-trip-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6381:6379"
  
  # user server redis
  redisuser:
    image: redis:alpine
    container_name: onepiece-user-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6382:6379"

  # location server redis
  redislocation:
    image: redis:alpine
    container_name: onepiece-location-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6383:6379"
  
  # redis chat
  redischat:
    image: redis:alpine
    container_name: onepiece-chat-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6384:6379"
  

  # event store db
  dbeventstore:
    image: kartoza/postgis:13.0
    container_name: onepiece-event-store-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 1113:5432
    volumes:
      - db_event_store:/var/lib/postgresql/data

  # trip server db
  dbtrip:
    image: kartoza/postgis:13.0
    container_name: onepiece-trip-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5433:5432
    volumes:
      - trip_data:/var/lib/postgresql/data

  # user server db
  dbuser:
    image: postgres:latest
    container_name: onepiece-user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5434:5432
    volumes:
      - user_data:/var/lib/postgresql/data

  # location server db
  dblocation:
    image: kartoza/postgis:13.0
    container_name: onepiece-location-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5435:5432
    volumes:
      - location_data:/var/lib/postgresql/data

  # article_data server db
  dbarticle:
    image: postgres:latest
    container_name: onepiece-article-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5436:5432
    volumes:
      - article_data:/var/lib/postgresql/data
  
  # db chat
  dbchat:
    image: postgres:latest
    container_name: onepiece-chat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5437:5432
    volumes:
      - chat_data:/var/lib/postgresql/data

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    links:
      - dblocation
    depends_on:
      - dblocation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - pgadmin:/root/.pgadmin
      - pgadmin:/var/lib/pgadmin
    ports:
      - "16543:80"

volumes:
  article_data:
  user_data:
  trip_data:
  location_data:
  chat_data:
  db_event_store:
  pgadmin:
    driver: local