version: "3"

services:
  # redis area
  # rate limit redis for gateway
  ratelimit:
    image: redis:alpine
    container_name: onepiece-gateway-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"

  # article server redis
  redisarticle:
    image: redis:alpine
    container_name: onepiece-article-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6380:6379"

  # trip server redis
  redistrip:
    image: redis:alpine
    container_name: onepiece-trip-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6381:6379"
  
  # user server redis
  redisuser:
    image: redis:alpine
    container_name: onepiece-user-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6382:6379"

  # location server redis
  redislocation:
    image: redis:alpine
    container_name: onepiece-location-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6383:6379"

  # article_data server db
  dbarticle:
    image: postgres:latest
    container_name: onepiece-user-article
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5432:5432
    volumes:
      - article_data:/var/lib/postgresql/data

  # trip server db
  dbtrip:
    image: postgres:latest
    container_name: onepiece-user-trip
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5433:5432
    volumes:
      - trip_data:/var/lib/postgresql/data

  # user server db
  dbuser:
    image: postgres:latest
    container_name: onepiece-user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5434:5432
    volumes:
      - user_data:/var/lib/postgresql/data

  # user server db
  dblocation:
    image: postgres:latest
    container_name: onepiece-location-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5435:5432
    volumes:
      - location_data:/var/lib/postgresql/data

volumes:
  article_data:
  user_data:
  trip_data:
  location_data:
    driver: local