version: "3.5"

services:
  # redis area
  # rate limit redis for gateway
  ratelimit:
    image: redis:alpine
    container_name: onepiece-gateway-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6378:6379"
    networks:
      services-network:
        aliases:
          - ratelimit

  # trip server redis
  redistrip:
    image: redis:alpine
    container_name: onepiece-trip-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6381:6379"
    networks:
      services-network:
        aliases:
          - redistrip
  
  # user server redis
  redisuser:
    image: redis:alpine
    container_name: onepiece-user-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6382:6379"
    networks:
      services-network:
        aliases:
          - redisuser

  # location server redis
  redislocation:
    image: redis:alpine
    container_name: onepiece-location-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6383:6379"
    networks:
      services-network:
        aliases:
          - redislocation

  # chat server redis
  redischat:
    image: redis:alpine
    container_name: onepiece-chat-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6384:6379"
    networks:
      services-network:
        aliases:
          - redischat

  # Relation DB Area
  # trip server db
  dbtrip:
    image: kartoza/postgis:13.0
    container_name: onepiece-trip-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5433:5432
    volumes:
      - trip_data:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - dbtrip

  # user server db
  dbuser:
    image: gangstead/postgis:latest-arm
    container_name: onepiece-user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5434:5432
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - dbuser

  # location server db
  dblocation:
    image: kartoza/postgis:13.0
    container_name: onepiece-location-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5435:5432
    volumes:
      - location_data:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - dblocation

  # chat server db
  dbchat:
    image: gangstead/postgis:latest-arm
    container_name: onepiece-chat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5437:5432
    volumes:
      - chat_data:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - dbchat

  # event store db
  dbeventstore:
    image: gangstead/postgis:latest-arm
    container_name: onepiece-event-store-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 1113:5432
    volumes:
      - db_event_store:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - dbeventstore

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    links:
      - dblocation
    depends_on:
      - dblocation
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - pgadmin:/root/.pgadmin
      - pgadmin:/var/lib/pgadmin
    ports:
      - "16543:80"
    networks:
      services-network:
        aliases:
          - pgadmin

  # RMQ Communication Area
  # rabbitmq area for serveral services communication will migrate all to use kafka later on if we have budget
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      services-network:
        aliases:
          - rabbitmq

  # KAFKA Communication Area
  # kafka area for serveral services communication will migrate all to confluent if we have budget
  # zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: onepiece-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      services-network:
        aliases:
          - zookeeper
    # volumes:
    #   - "zookeeper_data:/bitnami"
  kafka:
    # image: niks123123/kafka:2.7.0
    image: wurstmeister/kafka
    container_name: onepiece-kafka
    depends_on:
      - zookeeper
    # volumes:
    #   - "kafka_data:/bitnami"
    # environment:
    #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #     - ALLOW_PLAINTEXT_LISTENER=yes
    #     - KAFKA_LISTENERS=PLAINTEXT://:9092
    #     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
    # ports:
    #   - 9094:9094
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "onepiece-topic-chat:2:4,onepiece-topic-chat-event:2:4,onepiece-gateway-event:2:4,onepiece-user-event:2:4"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      services-network:
        aliases:
          - kafka


  # Service Area
  # gateway server
  gateway:
    build: ../one-piece-gateway
    container_name: onepiece-gateway
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9094 -wait tcp://ratelimit:6379 -wait tcp://redisuser:6379 npm run start:prod"
    depends_on:
      - zookeeper
      - kafka
      - ratelimit
      - redisuser
    environment:
      APPHOST: localhost
      APPPORT: 8080
      USERSERVER: ${USERSERVER}
      USERSERVERHOST: ${USERSERVERHOST}
      USERSERVERPORT: ${USERSERVERPORT}
      TRIPSERVER: ${TRIPSERVER}
      TRIPSERVERHOST: ${TRIPSERVERHOST}
      TRIPSERVERPORT: ${TRIPSERVERPORT}
      ARTICLEERVER: ${ARTICLESERVER}
      ARTICLEERVERHOST: ${ARTICLESERVERHOST}
      ARTICLEERVERPORT: ${ARTICLESERVERPORT}
      LOCATIONSERVER: ${LOCATIONSERVER}
      LOCATIONSERVERHOST: ${LOCATIONSERVERHOST}
      LOCATIONSERVERPORT: ${LOCATIONSERVERPORT}
      REDIS_URL: tcp://ratelimit:6379
      REDIS_BLACKLIST_URL: tcp://redisuser:6379
    ports:
      - 8080:8080
      - 84:84
    restart: on-failure
    networks:
      services-network:
        aliases:
          - gateway

  # user server
  service-user:
    build: ../one-piece-user
    container_name: onepiece-user-server
    # command: sh -c "./wait-for-it.sh -t 0 rabbitmq:5672 --strict -- npm run start:prod"
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9094 -wait tcp://rabbitmq:5672 -wait tcp://redisuser:6379 -wait tcp://redisuser:6379 -wait tcp://dbuser:5432 npm run start:prod"
    depends_on:
      - zookeeper
      - kafka
      - rabbitmq
      - redisuser
      - dbuser
      - gateway
    environment:
      APPHOST: localhost
      APPPORT: 7071
      DBHOST: dbuser
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: onepiece
      DBSCHEMA: public
      DBRATETABLE: user
      REDIS_URL: tcp://redisuser:6379
      JWTKEY: ${JWTKEY}
      JWTSECRET: ${JWTSECRET}
      CLOUDINARY_APINAME: ${CLOUDINARY_APINAME}
      CLOUDINARY_APIKEY: ${CLOUDINARY_APIKEY}
      CLOUDINARY_APISECRET: ${CLOUDINARY_APISECRET}
      CLOUDINARY_APIURL: ${CLOUDINARY_APIURL}
      EVENTSTOREPROTOCOL: ${EVENTSTOREPROTOCOL}
      EVENTSTOREHOSTNAME: ${EVENTSTOREHOSTNAME}
      EVENTSTORETCPPORT: ${EVENTSTORETCPPORT}
      GOOGLEAUTHID: ${GOOGLEAUTHID}
      GOOGLEAUTHSECRET: ${GOOGLEAUTHSECRET}
      GOOGLEAUTHCALLBACKURL: ${GOOGLEAUTHCALLBACKURL}
      GOOGLEMAILSUER: ${GOOGLEMAILSUER}
      GOOGLEMAILPASS: ${GOOGLEMAILPASS}
      FBAUTHID: ${FBAUTHID}
      FBAUTHSECRET: ${FBAUTHSECRET}
      FBAUTHCALLBACKURL: ${FBAUTHCALLBACKURL}
    ports:
      - 7071:7071
    restart: on-failure
    networks:
      services-network:
        aliases:
          - service-user

  # trip server
  service-trip:
    build: ../one-piece-trip
    container_name: onepiece-trip-server
    # command: sh -c "./wait-for-it.sh -t 0 rabbitmq:5672 --strict -- npm run start:prod"
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9094 -wait tcp://rabbitmq:5672 -wait tcp://redistrip:6379 -wait tcp://redisuser:6379 -wait tcp://dbtrip:5432 npm run start:prod"
    depends_on:
      - zookeeper
      - kafka
      - rabbitmq
      - redistrip
      - redisuser
      - dbtrip
      - gateway
    environment:
      APPHOST: localhost
      APPPORT: 7072
      DBHOST: dbtrip
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: onepiece
      DBSCHEMA: public
      DBRATETABLE: trip
      REDIS_URL: tcp://redistrip:6379
      REDIS_BLACKLIST_URL: tcp://redisuser:6379
      JWTKEY: ${JWTKEY}
      JWTSECRET: ${JWTSECRET}
      CLOUDINARY_APINAME: ${CLOUDINARY_APINAME}
      CLOUDINARY_APIKEY: ${CLOUDINARY_APIKEY}
      CLOUDINARY_APISECRET: ${CLOUDINARY_APISECRET}
      CLOUDINARY_APIURL: ${CLOUDINARY_APIURL}
      EVENTSTOREPROTOCOL: ${EVENTSTOREPROTOCOL}
      EVENTSTOREHOSTNAME: ${EVENTSTOREHOSTNAME}
      EVENTSTORETCPPORT: ${EVENTSTORETCPPORT}
      LOCATIONSERVER: ${LOCATIONSERVER}
      LOCATIONSERVERHOST: ${LOCATIONSERVERHOST}
      LOCATIONSERVERPORT: ${LOCATIONSERVERPORT}
    ports:
      - 7072:7072
    restart: on-failure
    networks:
      services-network:
        aliases:
          - service-trip

  # location service
  service-location:
    build: ../one-piece-location
    container_name: onepiece-location-server
    command: sh -c "./wait-for-it.sh -t 0 rabbitmq:5672 --strict -- npm run start:prod"
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9094 -wait tcp://rabbitmq:5672 -wait tcp://redislocation:6379 -wait tcp://redisuser:6379 -wait tcp://dblocation:5432 npm run start:prod"
    depends_on:
      - zookeeper
      - kafka
      - rabbitmq
      - redislocation
      - redisuser
      - dblocation
      - gateway
    environment:
      APPHOST: localhost
      APPPORT: 7074
      DBHOST: dblocation
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: onepiece
      DBSCHEMA: public
      DBRATETABLE: location
      REDIS_URL: tcp://redislocation:6379
      REDIS_BLACKLIST_URL: tcp://redisuser:6379
      JWTKEY: ${JWTKEY}
      JWTSECRET: ${JWTSECRET}
      EVENTSTOREPROTOCOL: ${EVENTSTOREPROTOCOL}
      EVENTSTOREHOSTNAME: ${EVENTSTOREHOSTNAME}
      EVENTSTORETCPPORT: ${EVENTSTORETCPPORT}
    ports:
      - 7074:7074
    restart: on-failure
    networks:
      services-network:
        aliases:
          - service-location

  # chat service
  service-chat:
    build: ../one-piece-chat
    container_name: onepiece-chat-server
    command: sh -c "dockerize -wait tcp://zookeeper:2181 -wait tcp://kafka:9094 -wait tcp://rabbitmq:5672 -wait tcp://redischat:6379 -wait tcp://redisuser:6379 -wait tcp://dbchat:5432 npm run start:prod"
    depends_on:
      - zookeeper
      - kafka
      - rabbitmq
      - redischat
      - redisuser
      - dbchat
      - gateway
    environment:
      APPHOST: localhost
      APPPORT: 7075
      DBHOST: dbchat
      DBPORT: 5432
      DBUSERNAME: postgres
      DBPASSWORD: 123
      DBDATABASE: onepiece
      DBSCHEMA: public
      DBRATETABLE: chat
      REDIS_URL: tcp://redischat:6379
      REDIS_BLACKLIST_URL: tcp://redisuser:6379
      JWTKEY: ${JWTKEY}
      JWTSECRET: ${JWTSECRET}
      EVENTSTOREPROTOCOL: ${EVENTSTOREPROTOCOL}
      EVENTSTOREHOSTNAME: ${EVENTSTOREHOSTNAME}
      EVENTSTORETCPPORT: ${EVENTSTORETCPPORT}
    ports:
      - 7075:7075
    restart: on-failure
    networks:
      services-network:
        aliases:
          - service-chat

networks:
  services-network:
    name: services-n
    driver: bridge

volumes:
  user_data:
  trip_data:
  location_data:
  chat_data:
  # zookeeper_data:
  # kafka_data:
  db_event_store:
  pgadmin:
    driver: local
