version: "3"

services:
  # redis area
  # rate limit redis for gateway
  ratelimit:
    image: redis:alpine
    container_name: onepiece-gateway-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
  
  # user server redis
  redisuser:
    image: redis:alpine
    container_name: onepiece-user-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6382:6379"

  # main server db
  dbuser:
    image: postgres:latest
    container_name: onepiece-user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: onepiece
    ports:
      - 5432:5432
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  user_data:
    driver: local